### ISSUE TITLE
Error SAXParseException for a LOAD query

### ISSUE THREAD

**Issue by BorderCloud** [blazegraph/database#101]
After a last build of the version 2.2.0, I have now this error for each LOAD request: ([see build](https://travis-ci.org/BorderCloud/tft-blazegraph/builds/415141056))
```
 SPARQL-UPDATE: updateStr=LOAD <http://bordercloud.github.io/rdf-tests/sparql11/data-sparql11/move/move-01.ttl> INTO GRAPH <http://example.org/g1>
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.openrdf.query.UpdateExecutionException: java.lang.RuntimeException: Could not load: url=http://bordercloud.github.io/rdf-tests/sparql11/data-sparql11/move/move-01.ttl, cause=org.openrdf.rio.RDFParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:295)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlUpdate(QueryServlet.java:458)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:239)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.openrdf.query.UpdateExecutionException: java.lang.RuntimeException: Could not load: url=http://bordercloud.github.io/rdf-tests/sparql11/data-sparql11/move/move-01.ttl, cause=org.openrdf.rio.RDFParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:569)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:470)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: org.openrdf.query.UpdateExecutionException: java.lang.RuntimeException: Could not load: url=http://bordercloud.github.io/rdf-tests/sparql11/data-sparql11/move/move-01.ttl, cause=org.openrdf.rio.RDFParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.bigdata.rdf.sparql.ast.eval.ASTEvalHelper.executeUpdate(ASTEvalHelper.java:1087)
	at com.bigdata.rdf.sail.BigdataSailUpdate.execute2(BigdataSailUpdate.java:152)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$UpdateTask.doQuery(BigdataRDFContext.java:1968)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.innerCall(BigdataRDFContext.java:1561)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:1526)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:739)
	... 4 more
Caused by: java.lang.RuntimeException: Could not load: url=http://bordercloud.github.io/rdf-tests/sparql11/data-sparql11/move/move-01.ttl, cause=org.openrdf.rio.RDFParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertLoadGraph(AST2BOpUpdate.java:1353)
	at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertUpdateSwitch(AST2BOpUpdate.java:412)
	at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertUpdate(AST2BOpUpdate.java:266)
	at com.bigdata.rdf.sparql.ast.eval.ASTEvalHelper.executeUpdate(ASTEvalHelper.java:1079)
	... 9 more
Caused by: org.openrdf.rio.RDFParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at org.semarglproject.sesame.rdf.rdfa.SesameRDFaParser.parse(SesameRDFaParser.java:111)
	at org.semarglproject.sesame.rdf.rdfa.SesameRDFaParser.parse(SesameRDFaParser.java:95)
	at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.doLoad(AST2BOpUpdate.java:1595)
	at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertLoadGraph(AST2BOpUpdate.java:1338)
	... 12 more
Caused by: org.semarglproject.rdf.ParseException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at org.semarglproject.rdf.rdfa.RdfaParser.processException(RdfaParser.java:1130)
	at org.semarglproject.source.XmlSource.process(XmlSource.java:50)
	at org.semarglproject.source.StreamProcessor.processInternal(StreamProcessor.java:87)
	at org.semarglproject.source.BaseStreamProcessor.process(BaseStreamProcessor.java:167)
	at org.semarglproject.source.BaseStreamProcessor.process(BaseStreamProcessor.java:154)
	at org.semarglproject.sesame.rdf.rdfa.SesameRDFaParser.parse(SesameRDFaParser.java:109)
	... 15 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at org.semarglproject.source.XmlSource.process(XmlSource.java:48)
	... 19 more
```
Thanks

**Comment by thompsonbry** [comment]
It looks like the URL might not be resolving to the contents of the TTL
file.

>>  http://bordercloud.github.io/rdf-tests/sparql11/data-
sparql11/move/move-01.ttl

This suggests that it is seeing an HTML page instead.

>>  The element type "hr" must be terminated by the matching end-tag
"</hr>".

The contents of the file should be as follows (I just followed the link)

@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix :      <http://example.org/> .

:jerry a foaf:Person .
:jerry foaf:givenName "Jerry" .
:jerry foaf:mbox  <mailto:jerry@example.org> .

So it appears to be complaining about the last line in that file. But no
"hr" (horizontal rule) tag exists in the resolve content.

Maybe you should try wget and observe the headers sent and conneg result.
If you own the server, check to see what is happening on the server. You
can also trace the conneg in blazegraph. It is likely happening in this
file:

bigdata-core/bigdata-sails/src/java/com/bigdata/rdf/sail/webapp/ConnegUtil.java
<https://github.com/blazegraph/database/blob/64bb8ca92eb063d45d68ec920a34b5321b80e2fe/bigdata-core/bigdata-sails/src/java/com/bigdata/rdf/sail/webapp/ConnegUtil.java>

Bryan

**Comment by thompsonbry** [comment]
When I inspect the document in the browser, it is actually an HTML
document.  I suspect a conneg issue.  Try a clean text version of the file
locally (copy and paste and make sure it is text, not html, inside of the
file).

Bryan

**Comment by BorderCloud** [comment]
I found. It's a problem with the redirection http->https with the LOAD queries. I had not this problem with the other databases.

```
LOAD <http://bordercloud.github.io/....ttl> => Error
LOAD <https://bordercloud.github.io/....ttl> => OK
```
I fix this problem of my side but I think, it's a good idea to enable the redirections for the LOAD queries.

Thanks.

(if it's not a bug, you can close this issue)

**Comment by thompsonbry** [comment]
Noted.  I am pretty sure that there is a way to configure the redirect
following behavior for the embedded jetty http client.  @beebs - do you
recall this off hand?  @michael?

Thanks,
Bryan
