### ISSUE TITLE
Blazegraph java API

### ISSUE THREAD

**Issue by raymanrt** [blazegraph/database#16]
Hi, I'am iterating a large resultset (5M of URIs) with blazegraph java api (openrdf based):
`
try {
	final TupleQueryResult results = repository
			.prepareTupleQuery(config.getSelectQuery())
			.evaluate();

	final Collection<String> uriGroup = new ArrayList<>();

	while(results.hasNext()) {
		final BindingSet result = results.next();
		final String uri = result.getBinding(variable).getValue().stringValue();
		uriGroup.add(uri);

		if(uriGroup.size() == batchSize) {
			makeConstruct(uriGroup, config, repository);
			uriGroup.clear();
		}
	}

	if(uriGroup.size() > 0) {
		makeConstruct(uriGroup, config, repository);
		uriGroup.clear();
	}

} catch (final Exception e) {
	e.printStackTrace();
}
`

For each group of uris (uriGroup) I perform another query on the server:
`
private void makeConstruct(final Collection<String> uris, final SparqlPumpConfig config, final RemoteRepository repository) {

    final String query = createConstruct(config, uris);

    try {
		final GraphQueryResult graph = repository
			.prepareGraphQuery(query)
			.evaluate();

		while(graph.hasNext()) {
			final Statement statement = graph.next();

			final String subjectUri = statement.getSubject().stringValue();
			final String propertyUri = statement.getPredicate().stringValue();
			final Object object = cast(statement.getObject());

			// ... do something ...

		}

                graph.close();

	} catch (final Exception e) {
		log.info("error executing query: {}", query);
		e.printStackTrace();
	}

}
`

Unfortunately in the middle of the execution the client stops reporting the following exception:
`
org.openrdf.query.QueryEvaluationException: java.io.IOException: Unkown record type: 10
	at org.openrdf.http.client.QueueCursor.checkException(QueueCursor.java:164)
	at org.openrdf.http.client.QueueCursor.getNextElement(QueueCursor.java:123)
	at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
	at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at com.bigdata.rdf.sail.webapp.client.RemoteRepositoryManager$2.hasNext(RemoteRepositoryManager.java:2227)
[...]
Caused by: java.io.IOException: Unkown record type: 10
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.parse(BinaryQueryResultParser.java:197)
	at com.bigdata.rdf.sail.webapp.client.BackgroundTupleResult.run(BackgroundTupleResult.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
`

Do you think am I using the API in the wrong way or maybe there's some bug?

Thanks,
 Riccardo

**Comment by beebs-systap** [comment]
Can you confirm the Sesame version you are using?

**Comment by raymanrt** [comment]
I've found the problem both with the maven dependency com.blazegraph.blazegraph-core 2.1.0 and with 2.2.0-SNAPSHOT. The former imports the 2.8.10 version of openrdf.

**Comment by raymanrt** [comment]
Just once the process finished correctly.
The following time it gave me the `Unkown record type` exception.

So I tried restarting the blazegraph server and in fact it lasted more time than the previous, but gave me a new exception: 

`
org.openrdf.query.QueryEvaluationException: java.io.IOException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response
	at org.openrdf.http.client.QueueCursor.checkException(QueueCursor.java:170)
	at org.openrdf.http.client.QueueCursor.getNextElement(QueueCursor.java:125)
	at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
	at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at com.bigdata.rdf.sail.webapp.client.RemoteRepositoryManager$3.hasNext(RemoteRepositoryManager.java:2355)
	at it.celi.dd.connector.SparqlBlazegraphPump.makeQueries(SparqlBlazegraphPump.java:161)
	at it.celi.dd.connector.SparqlBlazegraphPump.on(SparqlBlazegraphPump.java:141)
	at it.celi.overmind.disruptor.ItemReceiverPublisher.call(ItemReceiverPublisher.java:65)
	at it.celi.overmind.disruptor.ItemReceiverPublisher.call(ItemReceiverPublisher.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response
	at org.eclipse.jetty.client.util.InputStreamResponseListener$Input.failure(InputStreamResponseListener.java:320)
	at org.eclipse.jetty.client.util.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:286)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at info.aduna.io.IOUtil.readBytes(IOUtil.java:268)
	at info.aduna.io.IOUtil.readBytes(IOUtil.java:231)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readStringV2(BinaryQueryResultParser.java:343)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readString(BinaryQueryResultParser.java:320)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readQName(BinaryQueryResultParser.java:262)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.parse(BinaryQueryResultParser.java:183)
	at com.bigdata.rdf.sail.webapp.client.BackgroundTupleResult.run(BackgroundTupleResult.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.badMessage(HttpReceiverOverHTTP.java:277)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1351)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:142)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.readAndParse(HttpReceiverOverHTTP.java:107)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:70)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:65)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:75)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:100)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	... 1 more
2016-08-25 18:04:13,017 - INFO  - [pool-9-thread-1] - i.c.d.c.SparqlBlazegraphPump:148 - 
`

Any idea?

**Comment by beebs-systap** [comment]
Adding @igor-kim

**Comment by raymanrt** [comment]
And from another execution:
`
org.openrdf.query.QueryEvaluationException: java.io.IOException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response on HttpConnectionOverHTTP@693d3692(l:/192.168.3.224:47500 <-> r:linkeddata.xyz/138.201.89.100:9999,closed=false)[HttpChannelOverHTTP@2c3fa5d1(exchange=HttpExchange@655cd7f9 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@1dd94947(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@6d02afea(rsp=CONTENT,failure=null)[HttpParser{s=CLOSED,589824 of 0}]]]
	at org.openrdf.http.client.QueueCursor.checkException(QueueCursor.java:170)
	at org.openrdf.http.client.QueueCursor.getNextElement(QueueCursor.java:125)
	at info.aduna.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:91)
	at info.aduna.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:60)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at com.bigdata.rdf.sail.webapp.client.RemoteRepositoryManager$3.hasNext(RemoteRepositoryManager.java:2355)
	at it.celi.dd.connector.SparqlBlazegraphPump.makeQueries(SparqlBlazegraphPump.java:161)
	at it.celi.dd.connector.SparqlBlazegraphPump.on(SparqlBlazegraphPump.java:141)
	at it.celi.overmind.disruptor.ItemReceiverPublisher.call(ItemReceiverPublisher.java:65)
	at it.celi.overmind.disruptor.ItemReceiverPublisher.call(ItemReceiverPublisher.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response on HttpConnectionOverHTTP@693d3692(l:/192.168.3.224:47500 <-> r:linkeddata.xyz/138.201.89.100:9999,closed=false)[HttpChannelOverHTTP@2c3fa5d1(exchange=HttpExchange@655cd7f9 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@1dd94947(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@6d02afea(rsp=CONTENT,failure=null)[HttpParser{s=CLOSED,589824 of 0}]]]
	at org.eclipse.jetty.client.util.InputStreamResponseListener$Input.failure(InputStreamResponseListener.java:320)
	at org.eclipse.jetty.client.util.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:286)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at info.aduna.io.IOUtil.readBytes(IOUtil.java:268)
	at info.aduna.io.IOUtil.readBytes(IOUtil.java:231)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readStringV2(BinaryQueryResultParser.java:343)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readString(BinaryQueryResultParser.java:320)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.readQName(BinaryQueryResultParser.java:262)
	at org.openrdf.query.resultio.binary.BinaryQueryResultParser.parse(BinaryQueryResultParser.java:183)
	at com.bigdata.rdf.sail.webapp.client.BackgroundTupleResult.run(BackgroundTupleResult.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response on HttpConnectionOverHTTP@693d3692(l:/192.168.3.224:47500 <-> r:linkeddata.xyz/138.201.89.100:9999,closed=false)[HttpChannelOverHTTP@2c3fa5d1(exchange=HttpExchange@655cd7f9 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@1dd94947(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@6d02afea(rsp=CONTENT,failure=null)[HttpParser{s=CLOSED,589824 of 0}]]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.badMessage(HttpReceiverOverHTTP.java:288)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1362)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:123)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	... 1 more
`

**Comment by raymanrt** [comment]
No way to make it work!

I had to use an HTTP request bypassing the API.
