### ISSUE TITLE
Error when Creating New Namespace

### ISSUE THREAD

**Issue by shadefc09** [blazegraph/database#199]
I have bigdata installed and running on RHEL8. I have several namespaces create already and have not had an issue. Suddenly, if I try to create a new namespace, no matter what I name it, I get the error below.

I'm attempting to add the namespace on the blazegraph workbench where I created the other namespaces. I've tried to create it in both triple and quads mode. The existing namespaces are in quads mode.

```
namespace=test
java.util.concurrent.ExecutionException: java.lang.Exception: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "267;"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:294)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doCreateNamespace(MultiTenancyServlet.java:589)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "267;"
	at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:125)
	at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:62)
	at com.bigdata.rdf.sail.webapp.AbstractDelegateRestApiTask.call(AbstractDelegateRestApiTask.java:61)
	at com.bigdata.rdf.sail.webapp.RestApiCreateKBTask.call(RestApiCreateKBTask.java:71)
	at com.bigdata.rdf.sail.webapp.RestApiCreateKBTask.call(RestApiCreateKBTask.java:37)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "267;"
	at com.bigdata.rdf.store.AbstractTripleStore.create(AbstractTripleStore.java:2004)
	at com.bigdata.rdf.sail.CreateKBTask.createLTS(CreateKBTask.java:409)
	at com.bigdata.rdf.sail.CreateKBTask.access$000(CreateKBTask.java:62)
	at com.bigdata.rdf.sail.CreateKBTask$1.call(CreateKBTask.java:247)
	at com.bigdata.rdf.sail.CreateKBTask$1.call(CreateKBTask.java:241)
	at com.bigdata.rdf.sail.BigdataSail.getUnisolatedConnectionLocksAndRunLambda(BigdataSail.java:1450)
	at com.bigdata.rdf.sail.CreateKBTask.doRun(CreateKBTask.java:257)
	at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:104)
	... 9 more
Caused by: java.lang.NumberFormatException: For input string: "267;"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.bigdata.config.IntegerValidator.parse(IntegerValidator.java:72)
	at com.bigdata.config.IntegerValidator.parse(IntegerValidator.java:37)
	at com.bigdata.config.Configuration.getProperty(Configuration.java:291)
	at com.bigdata.btree.IndexMetadata.getProperty(IndexMetadata.java:2979)
	at com.bigdata.btree.IndexMetadata.<init>(IndexMetadata.java:2027)
	at com.bigdata.relation.AbstractRelation.newIndexMetadata(AbstractRelation.java:279)
	at com.bigdata.rdf.lexicon.LexiconRelation.getTerm2IdIndexMetadata(LexiconRelation.java:1323)
	at com.bigdata.rdf.lexicon.LexiconRelation.create(LexiconRelation.java:759)
	at com.bigdata.rdf.store.AbstractTripleStore.create(AbstractTripleStore.java:1864)
	... 16 more
```

**Comment by thompsonbry** [comment]
That is pretty odd. Can you paste a link to the source for the version you
are running?  In particular, I am interested in what this link corresponds
to.

at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: java.lang.RuntimeException:
java.lang.NumberFormatException: For input string: "267;"
	at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:125)

There are a few different sources for the properties used when creating or
opening a triple or quad store

- the properties configuration file
- properties for the specific create request
- durable properties written into the journal
- environment variables

I would like to understand which property it is complaining about. That
might indicate a cause.

Bryan

**Comment by shadefc09** [comment]
As soon as you said properties configuration file I went to look at my properties setup. I had semicolons at the end of the branching factors. I removed them and it is working properly.

To answer your question, I don't have a link to provide you, but here is the information from the workbench:
```
Build Version=2.1.6-SNAPSHOT

Build Git Commit=6b0c935523f5064b80279b30a5175a858cddd2a1

Build Git Branch=refs/heads/BLAZEGRAPH_2_1_6_RC
```

Thanks for the help!

**Comment by thompsonbry** [comment]
Cool
