### ISSUE TITLE
maven fails to build blazegraph-rpm artifact

### ISSUE THREAD

**Issue by otheus** [blazegraph/database#21]
Valid for BLAZEGRAPH_2_1_4, 2_1_2 and maybe others. In whichever way I try to build the "rpm artifact" I get a fatal error. 

```
$ rpm -q rpm-build
rpm-build-4.8.0-37.el6.x86_64

$ java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
```

The error presented (below) gives me now clue as to how to remedy this.
Here is the summary output of the build process:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Blazegraph RPM Package 2.1.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ blazegraph-rpm ---
[INFO]
[INFO] --- rpm-maven-plugin:2.1.5:version (default-version) @ blazegraph-rpm ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Blazegraph Deployment Artifacts .................... SUCCESS [  0.150 s]
[INFO] Blazegraph WAR (bigdata legacy context path) ....... SUCCESS [  3.534 s]
[INFO] Blazegraph Executable Jar (bigdata legacy path) .... SUCCESS [ 11.331 s]
[INFO] Blazegraph WAR ..................................... SUCCESS [  2.246 s]
[INFO] Blazegraph Executable Jar .......................... SUCCESS [  9.394 s]
[INFO] Blazegraph Debian Package .......................... SUCCESS [  7.610 s]
[INFO] Blazegraph RPM Package ............................. FAILURE [  0.046 s]
[INFO] Blazegraph Tarball Package ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.909 s
[INFO] Finished at: 2016-09-09T10:24:19+02:00
[INFO] Final Memory: 33M/195M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:version (default-version) on project blazegraph-rpm: Execution default-version of goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:version failed: Unable to load the mojo 'version' (or one of its required components) from the plugin 'org.codehaus.mojo:rpm-maven-plugin:2.1.5': java.util.NoSuchElementException
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.codehaus.mojo:rpm-maven-plugin:2.1.5:version
```

**Comment by otheus** [comment]
I also get this after checking out `BLAZEGRAPH_2_1_2`. So there's probably an unrecognized dependency problem here.

**Comment by layik** [comment]
Its is the same for my attempt at building a deb.
cc @beebs-systap

**Comment by beebs-systap** [comment]
For the RPM without signing, try `mvn package -P \!code-signing`.

**Comment by layik** [comment]
Are you changing directory into blazegraph-rpm?

That was my issue. Thanks Brad

**Comment by otheus** [comment]
@layik @beebs-systap  no go. Same error. Run maven with `-e` option:

```[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:version (default-version) on project blazegraph-rpm: Execution default-version of goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:version failed: Unable to load the mojo 'version' (or one of its required components) from the plugin 'org.codehaus.mojo:rpm-maven-plugin:2.1.5'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
....
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-version of goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:version failed: Unable to load the mojo 'version' (or one of its required components) from the plugin 'org.codehaus.mojo:rpm-maven-plugin:2.1.5'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
.....
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'version' (or one of its required components) from the plugin 'org.codehaus.mojo:rpm-maven-plugin:2.1.5'
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:551)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
        ... 21 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: org.codehaus.mojo:rpm-maven-plugin:2.1.5:version
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
        ... 22 more
Caused by: java.util.NoSuchElementException
        at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
        at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
        at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
        at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
```

**Comment by layik** [comment]
@otheus I am on Debian but see no reason why [this](https://github.com/blazegraph/database/tree/master/blazegraph-rpm) should not work.
clone repo
```
yum -y install rpm-build
cd database/blazegraph-rpm
mvn package
```

**Comment by otheus** [comment]
Sorry, my inbox is a mess, and I believe I found an RPM from reputable source. Nevertheless, please re-open.

3 Months after you closed the issue, someone else logged the bug on the "mojohouse" project: https://github.com/mojohaus/rpm-maven-plugin/issues/73 . It turns out that the `pom.xml` erroneously specifies _both_ an extensions "block", and an extensions -> true node. According to that post,  all versions after 3.2.5 including mine (3.3.9) will not work unless one or the other is removed. According to my tests, only removing the `<extensions>true</extensions>` from the `<plugins>` node resolved the problem.

Workaround:
```
 cd blazegraph-rpm
 sed -i '\%<extensions>true</extensions>%d' pom.xml
 mvn package
```
