### ISSUE TITLE
war file: bigdata.jnl not found

### ISSUE THREAD

**Issue by mnscholz** [blazegraph/database#41]
Hi,

I downloaded the release war-file and tried to deploy it on tomcat.

However, the workbench does not load and in the tomcat logs I get 
that file bigdata.jnl cannot be accessed. I searched for the file but it doesn't seem to exist on the server.
Do I have to also install the rpm/dep or anything else?

Is there a file where blazegraph writes own logs to? 

Can someone point me to some useful documentation for running blazegraph with tomcat?

Thanks!
Martin

Here is the exception stack:
`SEVERE: Exception sending context initialized event to listener instance of class com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener
java.lang.RuntimeException: java.lang.RuntimeException: file=bigdata.jnl
        at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.openIndexManager(BigdataRDFServletContextListener.java:805)
        at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.contextInitialized(BigdataRDFServletContextListener.java:277)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: file=bigdata.jnl
        at com.bigdata.journal.FileMetadata.<init>(FileMetadata.java:851)
        at com.bigdata.journal.FileMetadata.createInstance(FileMetadata.java:1513)
        at com.bigdata.journal.AbstractJournal.<init>(AbstractJournal.java:1156)
        at com.bigdata.journal.Journal.<init>(Journal.java:276)
        at com.bigdata.journal.Journal.<init>(Journal.java:269)
        at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.openIndexManager(BigdataRDFServletContextListener.java:799)
        ... 14 more
Caused by: java.io.FileNotFoundException: bigdata.jnl (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at com.bigdata.journal.FileMetadata.reopenChannel(FileMetadata.java:1195)
        at com.bigdata.journal.FileMetadata.access$000(FileMetadata.java:58)
        at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1163)
        at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1153)
        at com.bigdata.journal.FileMetadata.<init>(FileMetadata.java:464)
        ... 19 more`

**Comment by beebs-systap** [comment]
Hello,

Please see if one of the suggestions described [here](https://wiki.blazegraph.com/wiki/index.php/NanoSparqlServer#Common_Startup_Problems) works for you. You may need to either add the path to the journal file as a startup parameter to Tomcat or edit the RWStore.properties.

The logging is done to the catalina.out for Tomcat in the war / Tomcat deployment model.

**Comment by mnscholz** [comment]
Hi,

thanks for the help!
Rather late (the holidays...) I want to report that I got blazegraph running on tomcat.

There were two problems:
1) the blazegraph.war release file does not contain blazegraph.jnl. I downloaded the source code, compiled it and got the jnl (called blazegraph.jnl, not bigdata.jnl).
2) despite the release being called blazegraph.war, in the RWStore.properties (and other .properties files), the library is called bigdata.jnl, not blazegraph.jnl. I changed them to the latter and used an absolute path.

After restarting tomcat a couple of times, blazegraph works fine now.

**Comment by thompsonbry** [comment]
The .jnl files contain the data for the database.  They are initially
created if they do not exist.

Just FYI.

Thanks,
Bryan

**Comment by mnscholz** [comment]
Good to know! So finally it seems the problem was that blazegraph/tomcat could not create the file due to missing permissions.

Thanks!
Martin

**Comment by nvbach91** [comment]
Blazegraph by default will create the `bigdata.jnl` file inside he folder where the servlet container is run. Usually that folder is protected so the `jnl` file can't be created. You should pick another location by defining an absolute path of in the properties files of Blazegraph.

Solution:

change
```
./webapps/blazegraph/WEB-INF/web.xml
line:42:<param-value>RWStore.properties</param-value>
./webapps/blazegraph/WEB-INF/GraphStore.properties
line:12:com.bigdata.journal.AbstractJournal.file=bigdata.jnl
./webapps/blazegraph/WEB-INF/classes/RWStore.properties
line:12:com.bigdata.journal.AbstractJournal.file=bigdata.jnl
```
to
```
./webapps/blazegraph/WEB-INF/web.xml
line:42:<param-value>/opt/tomcat/webapps/blazegraphpublic/WEB-INF/RWStore.properties</param-value>
./webapps/blazegraph/WEB-INF/GraphStore.properties
line:12:com.bigdata.journal.AbstractJournal.file=/your/existing/desired/path/bigdata.jnl
./webapps/blazegraph/WEB-INF/classes/RWStore.properties
line:12:com.bigdata.journal.AbstractJournal.file=/your/existing/desired/path/bigdata.jnl
```

also, you might need to
```
chown tomcat:tomcat /your/existing/desired/path/
```

link: https://github.com/blazegraph/database/wiki/NanoSparqlServer#common-startup-problems
