### ISSUE TITLE
Java POST returns a 400

### ISSUE THREAD

**Issue by redskate** [blazegraph/database#49]
Dear Blazegraph community - (sorry for formatting, I cannot get it better...)

using bigdata 
Tue Jan 24 18:03:47 CET 2017
Mac OS X/10.11.6 x86_64
Mac OS X 10.11.6 x86_64 #CPU=8
Oracle Corporation 1.8.0_25
freeMemory=137061912
buildVersion=2.1.4
gitCommit=738d05f08cffd319233a4bfbb0ec2a858e260f9c

I am having some issues transmitting a POST request with a SPARQL-UPDATE query inside using Java. Yes, I am using HttpURLConnection to post the query to Blazegraph.

Suppose http://13.0.2.130:8034/bigdata/namespace/demoEXTERNALULTIREP/sparql be a valid repo URL, sending even a simple query returns in the Java code an HTTP 400

String contenttype="application/x-www-form-urlencoded; charset=UTF-8";
			String accept = "*/*";
			String acceptlanguage = "en-US,de;q=0.7,en;q=0.3";
			String acceptencoding = "gzip, deflate";
urlquery="http://13.0.2.130:8034/bigdata/namespace/demoEXTERNALULTIREP/sparql";
			
data = "query=INSERT {<http://xx.ch/lod/base> a \"test\"} WHERE {}";
			URL myURL = new URL(urlquery);
			String host = myURL.getHost()+":"+(myURL.getPort()!=80?myURL.getPort():"");
			HttpURLConnection urlconn = (HttpURLConnection)myURL.openConnection();
			urlconn.setDoInput(true);
			urlconn.setDoOutput(true);
			urlconn.setRequestMethod("POST");
			if (!user.equals("") && !passwd.equals(""))
			{
				String userCredentials = user+":"+passwd;
				String basicAuth = "Basic " + new String(S2MP.b46encode(userCredentials.getBytes()));
				urlconn.setRequestProperty ("Authorization", basicAuth);
			}
			urlconn.setRequestProperty("Host", host);
			urlconn.setRequestProperty("Accept", accept);
			urlconn.setRequestProperty("Accept-Language", acceptlanguage);
			urlconn.setRequestProperty("Accept-Encoding", acceptencoding);
			urlconn.setRequestProperty("Content-Type", contenttype);
			urlconn.setRequestProperty("Content-Length", String.valueOf(data.length()));
			
			urlconn.setUseCaches(false);
			urlconn.setConnectTimeout(10000);
			urlconn.setReadTimeout(10000);
			urlconn.connect();
			// myURLConnection.getOutputStream().write(bytes);
			OutputStreamWriter out = new OutputStreamWriter(urlconn.getOutputStream());
			out.write(data);
			out.close();
	        int HttpResult = urlconn.getResponseCode();
	        if (HttpResult == HttpURLConnection.HTTP_OK) {
				InputStream is = urlconn.getInputStream();
				BufferedReader reader = new BufferedReader( new InputStreamReader( is )  );
				reader.close();
	        }

This code does not accomplish an UPDATE (no data is updated).
The same code but with "GET" returns an HTTP 200. 

<b>What should I do in order to be able to post this SPARQL-UPDATE query correctly ?</b>

Thanks a lot in advance!

PS: To say the truth, this Java code returns a 400 even if I do not send any data. 

PS2: Blazegraph threw the following exception (although the same query inside the workbench is adding one statement):

ERROR: BigdataRDFServlet.java:214: cause=java.util.concurrent.ExecutionException: org.openrdf.query.MalformedQueryException: Encountered " "insert" "INSERT "" at line 1, column 1.
Was expecting one of:
    "base" ...
    "prefix" ...
    "select" ...
    "construct" ...
    "describe" ...
    "ask" ...
    , query=SPARQL-QUERY: queryStr=INSERT {<http://xx.ch/lod/base> a "test"} WHERE {}
java.util.concurrent.ExecutionException: org.openrdf.query.MalformedQueryException: Encountered " "insert" "INSERT "" at line 1, column 1.
Was expecting one of:
    "base" ...
    "prefix" ...
    "select" ...
    "construct" ...
    "describe" ...
    "ask" ...
    
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:281)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:653)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:273)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1096)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openrdf.query.MalformedQueryException: Encountered " "insert" "INSERT "" at line 1, column 1.
Was expecting one of:
    "base" ...
    "prefix" ...
    "select" ...
    "construct" ...
    "describe" ...
    "ask" ...
    
	at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:400)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:716)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:670)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: com.bigdata.rdf.sail.sparql.ast.ParseException: Encountered " "insert" "INSERT "" at line 1, column 1.
Was expecting one of:
    "base" ...
    "prefix" ...
    "select" ...
    "construct" ...
    "describe" ...
    "ask" ...
    
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.generateParseException(SyntaxTreeBuilder.java:9718)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.jj_consume_token(SyntaxTreeBuilder.java:9585)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Query(SyntaxTreeBuilder.java:337)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.QueryContainer(SyntaxTreeBuilder.java:212)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.parseQuery(SyntaxTreeBuilder.java:32)
	at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:336)
	... 7 more

**Comment by redskate** [comment]
The solution:

in the data section there must be "update=" instead of "query="
