### ISSUE TITLE
N-Triples files aren't read if blank node label starts withnumber

### ISSUE THREAD

**Issue by retog** [blazegraph/database#5]
_:1 <http://example.org/p> "o".

the blank node identifier seems legal as https://www.w3.org/TR/n-triples/ says: "The characters _ and [0-9] may appear anywhere in a blank node label."

But inserting that in blazegrah results in:

```ERROR: INSERT-WITH-BODY: baseURI=http://lindas.zazuko.com:9999/blazegraph/namespace/swisstopo/sparql, Content-Type=text/plain, context-uri=[]
java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: Expected a letter, found: 1 [line 1]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:281)
	at com.bigdata.rdf.sail.webapp.InsertServlet.doPostWithBody(InsertServlet.java:203)
	at com.bigdata.rdf.sail.webapp.InsertServlet.doPost(InsertServlet.java:119)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:308)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:192)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openrdf.rio.RDFParseException: Expected a letter, found: 1 [line 1]
	at org.openrdf.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:348)
	at org.openrdf.rio.helpers.RDFParserBase.reportError(RDFParserBase.java:608)
	at org.openrdf.rio.ntriples.NTriplesParser.reportError(NTriplesParser.java:596)
	at org.openrdf.rio.ntriples.NTriplesParser.parseNodeID(NTriplesParser.java:455)
	at org.openrdf.rio.ntriples.NTriplesParser.parseSubject(NTriplesParser.java:343)
	at org.openrdf.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:282)
	at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:193)
	at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:132)
	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:305)
	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithBodyTask.call(InsertServlet.java:226)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more```

**Comment by beebs-systap** [comment]
@retog Would you mind creating a [JIRA](https://jira.blazegraph.com/) ticket for this one?

**Comment by beebs-systap** [comment]
Thx!   Agreed on the issues as linked data...someday... 👍
