### ISSUE TITLE
IllegalStateException: Form too large when adding ontology

### ISSUE THREAD

**Issue by Evertude** [blazegraph/database#65]
Hello Blazegraph Team,

I want to add an ontology file of about 125MB into Blazegraph Workbench. 
When I do so, the workbench tells me ERROR: Could not contact server and I see two warnings on the console.

Although this seems like a Jetty problem (the stack trace is below), maybe you can send several requests so that this problem doesn't occur.

WARN : ServletHandler.java:626: /blazegraph/namespace/test/sparql
java.lang.IllegalStateException: Form too large: 35166271 > 10485760
        at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:3
64)
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.jav
a:302)
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
        at org.eclipse.jetty.server.Request.getParameter(Request.java:827)
        at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:256)
        at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancySe
rvlet.java:193)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java
:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:539)
        at java.lang.Thread.run(Unknown Source)
WARN : HttpParser.java:1358: badMessage: java.lang.IllegalStateException: too mu
ch data after closed for HttpChannelOverHttp@24cb80e8{r=1,c=false,a=IDLE,uri=-}
WARN : ServletHandler.java:626: /blazegraph/namespace/test/sparql
java.lang.IllegalStateException: Form too large: 35166271 > 10485760
        at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:3
64)
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.jav
a:302)
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
        at org.eclipse.jetty.server.Request.getParameter(Request.java:827)
        at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:256)
        at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancySe
rvlet.java:193)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java
:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:539)
        at java.lang.Thread.run(Unknown Source)
WARN : HttpParser.java:1358: badMessage: java.lang.IllegalStateException: too mu
ch data after closed for HttpChannelOverHttp@5f454652{r=1,c=false,a=IDLE,uri=-}
WARN : ServletHandler.java:626: /blazegraph/namespace/test/sparql
java.lang.IllegalStateException: Form too large: 35166261 > 10485760
        at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:3
64)
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.jav
a:302)
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
        at org.eclipse.jetty.server.Request.getParameter(Request.java:827)
        at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:256)
        at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancySe
rvlet.java:193)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java
:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:539)
        at java.lang.Thread.run(Unknown Source)
WARN : HttpParser.java:1358: badMessage: java.lang.IllegalStateException: too much data after closed for HttpChannelOverHttp@1e784c69{r=1,c=false,a=IDLE,uri=-}

**Comment by Evertude** [comment]
Okay, I just found my problem: I set the UPDATE Type to File Path or URL (default I think) instead of RDF Data. With RDF Data it works. 

You should maybe consider mentioning that somewhere because I entered a File Path to a RDF file.
