### ISSUE TITLE
502 Proxy Error, when loading 2.6Gb file via the web interface

### ISSUE THREAD

**Issue by VonUniGE** [blazegraph/database#8]
Hello,

I'm trying to load a 2.6Gb turtle file via the update panel of the web interface with the following command:

`load <file:///mnt/data/a0001.ttl>`

It gives me:

```
ERROR:

502 Proxy Error

Proxy Error
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /blazegraph/namespace/test/sparql.
Reason: Error reading from remote server
```

I'm not sure if it's a bug or if it's a problem related to my configuration, but as the url is pointing to the filesystem I don't understand why a proxy is involved.

**Comment by beebs-systap** [comment]
Thank you.  Can you post the output of the status page http://localhost:9999/blazegraph/#status?  How is Blazegraph being deployed?

**Comment by VonUniGE** [comment]
Here is the output of `http://localhost:9999/blazegraph/#status`:

```
Build Version=2.1.0

Build Git Commit=c7075f1a635174b709d5bf2f3bfa92365fa60f51

Build Git Branch=refs/heads/BLAZEGRAPH_RELEASE_2_1_0

Accepted query count=9

Running query count=0

Show queries, query details.


/GeoSpatial/bigMinCalculationTimeMS=0
/GeoSpatial/filterCalculationTimeMS=0
/GeoSpatial/geoSpatialSearchRequests=0
/GeoSpatial/geoSpatialServiceCallSubRangeTasks=0
/GeoSpatial/geoSpatialServiceCallTasks=0
/GeoSpatial/rangeCheckCalculationTimeMS=0
/GeoSpatial/zOrderIndexHitRatio=null
/GeoSpatial/zOrderIndexHits=0
/GeoSpatial/zOrderIndexMisses=0
/GeoSpatial/zOrderIndexScannedValues=0
/blockedWorkQueueCount=0
/blockedWorkQueueRunningTotal=3451
/deadlineQueueSize=0
/operatorActiveCount=0
/operatorHaltCount=4554
/operatorStartCount=4554
/operatorTasksPerQuery=569.25
/queriesPerSecond=0.4151746328299341
/queryDoneCount=8
/queryErrorCount=0
/queryStartCount=8
```

I've deployed bigdata.war on Apache Tomcat/8.0.32 by unzipping the war in the webapps directory.

The two only things I've modified from the default configuration is the location of the property file in web.xml and the location of the AbstractJournal file in the property file.

**Comment by beebs-systap** [comment]
This could be a Tomcat time-out issue on waiting for the response.   I would be curious if you run `./scripts/startBlazegraph.sh` and try the same curl from localhost:9999, if you get the same error.

**Comment by VonUniGE** [comment]
I've build blazegraph 2.1.0 from this repository and launch `./startBlazegraph.sh`. Then I sent the following request : 
```curl -X POST http://localhost:9999/blazegraph/sparql --data-urlencode 'update=LOAD <file:///mnt/data/test/a0001.ttl>;```
The process finished without errors, created a 6.2Gb `blazegraph.jnl` from a 2.6Gb ttl  file and gives me this answer:
```
<p>totalElapsed=2248785ms, elapsed=2248690ms, connFlush=0ms, batchResolve=0, whereClause=0ms, deleteClause=0ms, insertClause=0ms</p
><hr><p>COMMIT: totalElapsed=2261800ms, commitTime=1464107363696, mutationCount=37226743</p
```
but then trying a request from the documentation:
```
curl -X POST http://localhost:9999/blazegraph/sparql --data-urlencode 'query=SELECT * { ?s ?p ?o } LIMIT 1' -H 'Accept:application/rdf+xml'
```
gives me an error:
```
ERROR: QueryEngine.java:1101: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.consumeChunk(ChunkedRunningQuery.java:363)
	at com.bigdata.bop.engine.QueryEngine$QueryEngineTask.run(QueryEngine.java:1084)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
ERROR: QueryEngine.java:1101: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.consumeChunk(ChunkedRunningQuery.java:363)
	at com.bigdata.bop.engine.QueryEngine$QueryEngineTask.run(QueryEngine.java:1084)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Haltable.java:469: com.bigdata.bop.join.PipelineJoin$JoinTask{ joinOp=com.bigdata.bop.join.PipelineJoin[3]()[ BOp.bopId=3, JoinAnnotations.constraints=null, AST2BOpBase.simpleJoin=true, BOp.evaluationContext=ANY, AccessPathJoinAnnotations.predicate=com.bigdata.rdf.spo.SPOPredicate[1](s=null, p=null, o=null, --anon-2=null)[ IPredicate.relationName=[kb.spo], IPredicate.timestamp=1464108246720, BOp.bopId=1, AST2BOpBase.estimatedCardinality=37226743, AST2BOpBase.originalIndex=SPOC, IPredicate.flags=[KEYS,VALS,READONLY,PARALLEL], IPredicate.accessPathFilter=cutthecrap.utils.striterators.NOPFilter@2a9eeb5c{annotations=null,filterChain=[com.bigdata.bop.rdf.filter.StripContextFilter(), com.bigdata.bop.ap.filter.DistinctFilter()]}]]} : isFirstCause=true : java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.acceptChunk(ChunkedRunningQuery.java:331)
	at com.bigdata.bop.engine.QueryEngine.acceptChunk(QueryEngine.java:1149)
	at com.bigdata.bop.engine.StandaloneChunkHandler.handleChunk(StandaloneChunkHandler.java:66)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputChunk(ChunkedRunningQuery.java:1670)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.addReorderAllowed(ChunkedRunningQuery.java:1599)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1540)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1424)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:59)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:14)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.overflow(AbstractUnsynchronizedArrayBuffer.java:287)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add2(AbstractUnsynchronizedArrayBuffer.java:215)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add(AbstractUnsynchronizedArrayBuffer.java:173)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.handleJoin2(PipelineJoin.java:1868)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.call(PipelineJoin.java:1684)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.runOneTask(PipelineJoin.java:1087)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.call(PipelineJoin.java:995)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.consumeSource(PipelineJoin.java:729)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:623)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:382)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1317)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:897)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:792)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
ERROR: QueryEngine.java:1101: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.consumeChunk(ChunkedRunningQuery.java:363)
	at com.bigdata.bop.engine.QueryEngine$QueryEngineTask.run(QueryEngine.java:1084)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Banner.java:160: Uncaught exception in thread
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.access$300(ChunkedRunningQuery.java:90)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:828)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
WARN : Haltable.java:474: com.bigdata.bop.join.PipelineJoin$JoinTask{ joinOp=com.bigdata.bop.join.PipelineJoin[3]()[ BOp.bopId=3, JoinAnnotations.constraints=null, AST2BOpBase.simpleJoin=true, BOp.evaluationContext=ANY, AccessPathJoinAnnotations.predicate=com.bigdata.rdf.spo.SPOPredicate[1](s=null, p=null, o=null, --anon-2=null)[ IPredicate.relationName=[kb.spo], IPredicate.timestamp=1464108246720, BOp.bopId=1, AST2BOpBase.estimatedCardinality=37226743, AST2BOpBase.originalIndex=SPOC, IPredicate.flags=[KEYS,VALS,READONLY,PARALLEL], IPredicate.accessPathFilter=cutthecrap.utils.striterators.NOPFilter@2a9eeb5c{annotations=null,filterChain=[com.bigdata.bop.rdf.filter.StripContextFilter(), com.bigdata.bop.ap.filter.DistinctFilter()]}]]} : isFirstCause=false : java.lang.RuntimeException: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.RuntimeException: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.handleJoin2(PipelineJoin.java:1961)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.call(PipelineJoin.java:1684)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.runOneTask(PipelineJoin.java:1087)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.call(PipelineJoin.java:995)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.consumeSource(PipelineJoin.java:729)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:623)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:382)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1317)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:897)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:792)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.acceptChunk(ChunkedRunningQuery.java:331)
	at com.bigdata.bop.engine.QueryEngine.acceptChunk(QueryEngine.java:1149)
	at com.bigdata.bop.engine.StandaloneChunkHandler.handleChunk(StandaloneChunkHandler.java:66)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputChunk(ChunkedRunningQuery.java:1670)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.addReorderAllowed(ChunkedRunningQuery.java:1599)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1540)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1424)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:59)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:14)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.overflow(AbstractUnsynchronizedArrayBuffer.java:287)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add2(AbstractUnsynchronizedArrayBuffer.java:215)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add(AbstractUnsynchronizedArrayBuffer.java:173)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.handleJoin2(PipelineJoin.java:1868)
	... 17 more
ERROR: ChunkedRunningQuery.java:1835: Could not notify query controller: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.consumeChunk(ChunkedRunningQuery.java:363)
	at com.bigdata.bop.engine.ChunkedRunningQuery.haltOp(ChunkedRunningQuery.java:384)
	at com.bigdata.bop.engine.ChunkedRunningQuery$SendHaltMessageTask.run(ChunkedRunningQuery.java:1825)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
WARN : Haltable.java:474: com.bigdata.bop.join.PipelineJoin$JoinTask{ joinOp=com.bigdata.bop.join.PipelineJoin[3]()[ BOp.bopId=3, JoinAnnotations.constraints=null, AST2BOpBase.simpleJoin=true, BOp.evaluationContext=ANY, AccessPathJoinAnnotations.predicate=com.bigdata.rdf.spo.SPOPredicate[1](s=null, p=null, o=null, --anon-2=null)[ IPredicate.relationName=[kb.spo], IPredicate.timestamp=1464108246720, BOp.bopId=1, AST2BOpBase.estimatedCardinality=37226743, AST2BOpBase.originalIndex=SPOC, IPredicate.flags=[KEYS,VALS,READONLY,PARALLEL], IPredicate.accessPathFilter=cutthecrap.utils.striterators.NOPFilter@2a9eeb5c{annotations=null,filterChain=[com.bigdata.bop.rdf.filter.StripContextFilter(), com.bigdata.bop.ap.filter.DistinctFilter()]}]]} : isFirstCause=false : java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.call(PipelineJoin.java:1027)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.consumeSource(PipelineJoin.java:729)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:623)
	at com.bigdata.bop.join.PipelineJoin$JoinTask.call(PipelineJoin.java:382)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1317)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:897)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:792)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.handleJoin2(PipelineJoin.java:1961)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.call(PipelineJoin.java:1684)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.runOneTask(PipelineJoin.java:1087)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$BindingSetConsumerTask.call(PipelineJoin.java:995)
	... 14 more
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.bigdata.bop.engine.ChunkedRunningQuery.scheduleNext(ChunkedRunningQuery.java:428)
	at com.bigdata.bop.engine.ChunkedRunningQuery.acceptChunk(ChunkedRunningQuery.java:331)
	at com.bigdata.bop.engine.QueryEngine.acceptChunk(QueryEngine.java:1149)
	at com.bigdata.bop.engine.StandaloneChunkHandler.handleChunk(StandaloneChunkHandler.java:66)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputChunk(ChunkedRunningQuery.java:1670)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.addReorderAllowed(ChunkedRunningQuery.java:1599)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1540)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1424)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:59)
	at com.bigdata.relation.accesspath.UnsyncLocalOutputBuffer.handleChunk(UnsyncLocalOutputBuffer.java:14)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.overflow(AbstractUnsynchronizedArrayBuffer.java:287)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add2(AbstractUnsynchronizedArrayBuffer.java:215)
	at com.bigdata.relation.accesspath.AbstractUnsynchronizedArrayBuffer.add(AbstractUnsynchronizedArrayBuffer.java:173)
	at com.bigdata.bop.join.PipelineJoin$JoinTask$AccessPathTask.handleJoin2(PipelineJoin.java:1868)
	... 17 more


```

**Comment by beebs-systap** [comment]
That error typically indicates the code was compiled with Java 8 and being run in Java 7.  Is that possible in your case?    You could try a full local rebuild with `./scripts/mavenInstall.sh` to make sure you are build with the same Java version you're using in execution.

**Comment by VonUniGE** [comment]
Unfortunately, I can't install a build environment on the deployment server. But I can say that the build was done with
```
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
and the deployment server runs
```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by VonUniGE** [comment]
Hello,

I've requested (and obtained) a dedicated virtual machine with 1To of disk and 12Gb of memory. I've build and installed blazegraph 2.1.1 from this repository. Loading the same 2.6Gb file takes 1951153ms (~32 min.) and generated a 6.2Gb blazegraph.jnl. All SPARQL requests are now sucessful.

Does the request time and the size of the generated file seem correct?

Thank you.

**Comment by beebs-systap** [comment]
OK -- good news.   That times doesn't seem outside of the range that we'd expect.    There are likely some tuning options if you use the [DataLoader](https://wiki.blazegraph.com/wiki/index.php/Bulk_Data_Load) and [InlineIVs](https://wiki.blazegraph.com/wiki/index.php/InlineIVs).
