### ISSUE TITLE
Fatal Error: The markup in the document preceding the root element must be well-formed.

### ISSUE THREAD

**Issue by loretoparisi** [blazegraph/database#84]
I have successfully completed the split of the latest wikidata entities dump `wikidata-20180319-all-BETA.ttl.gz`into chunks and now I'm trying to import this split into Blazegraph, using the [wikidata-query-rdf](https://github.com/wikimedia/wikidata-query-rdf/blob/master/docs/getting-started.md) distribution. The BlazeGraph version in use was:

```
Linux/4.4.0-108-generic amd64
Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz Family 6 Model 62 Stepping 4, GenuineIntel #CPU=12
Oracle Corporation 1.8.0_151
freeMemory=750345360
buildVersion=2.1.5-SNAPSHOT
gitCommit=8ff64aab6071b5e591e80676809e43f0ddb8ad49
```

I have started Blazegraph like `./runBlazegraph.sh 2>&1 >> ./out.log &`. The service seems to be ok since I can see that it is running (with no data at this moment):

```
root       202  6.7 18.9 24807644 3106392 ?    Sl   08:25   0:38 java -server -XX:+UseG1GC -Xmx16g -Xloggc:/var/log/wdqs/wdqs-blazegraph_jvm_gc.%p-%t.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintAdaptiv
```

I have then started the split data import `nohup ./loadRestAPI.sh -n wdq -d $ROOT/data/split &`, and I have got immediately an error from Blazegraph about the markup formatting:

```
[Fatal Error] :1:527: The element type "link" must be terminated by the matching end-tag "</link>".
[Fatal Error] :1:426: The element type "link" must be terminated by the matching end-tag "</link>".
[Fatal Error] :1:420: The element type "link" must be terminated by the matching end-tag "</link>".
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
```

So the import has automatically stopped.

**NOTES**
- I have used the default configuration in `/root/blazegraph/RWStore.properties` (no changes applied by my side)
- During the server startup I can see some warnings and the exception: `java.nio.file.NoSuchFileException: ./mwservices.json`, following the stacktrace:

```
08:25:12.132 [main] WARN  com.bigdata.rdf.ServiceProviderHook IP: UA: - Running.
2018-03-28 08:25:13.810:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@244038d0{/bigdata,file:/tmp/jetty-localhost-9999-blazegraph-service-0.3.1-SNAPSHOT.war-_bigdata-any-6877460072997126380.dir/webapp/,AVAILABLE}{file:/root/blazegraph/blazegraph-service-0.3.1-SNAPSHOT.war}
2018-03-28 08:25:13.811:WARN:oejsh.RequestLogHandler:main: !RequestLog
2018-03-28 08:25:13.830:INFO:oejs.ServerConnector:main: Started ServerConnector@30845c90{HTTP/1.1}{localhost:9999}
2018-03-28 08:25:13.830:INFO:oejs.Server:main: Started @10086ms
08:25:13.478 [main] INFO  o.w.q.r.b.mwapi.MWApiServiceFactory IP: UA: - Loading MWAPI service configuration from ./mwservices.json
08:25:13.486 [main] WARN  o.w.q.r.b.mwapi.MWApiServiceFactory IP: UA: - MW Service registration failed.
java.nio.file.NoSuchFileException: ./mwservices.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at org.wikidata.query.rdf.blazegraph.mwapi.MWApiServiceFactory.<init>(MWApiServiceFactory.java:101)
	at org.wikidata.query.rdf.blazegraph.mwapi.MWApiServiceFactory.register(MWApiServiceFactory.java:116)
	at org.wikidata.query.rdf.blazegraph.WikibaseContextListener.initializeServices(WikibaseContextListener.java:93)
	at org.wikidata.query.rdf.blazegraph.WikibaseContextListener.contextInitialized(WikibaseContextListener.java:216)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1341)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1334)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
08:25:13.491 [main] WARN  o.w.q.r.b.WikibaseContextListener IP: UA: - Failed reading from whitelist file
08:25:13.525 [main] INFO  o.w.q.r.b.WikibaseContextListener IP: UA: - Wikibase services initialized.
08:25:13.756 [main] INFO  o.w.q.r.b.t.ThrottlingFilter IP: UA: - ThrottlingFilter MBean registered as org.wikidata.query.rdf.blazegraph.throttling.ThrottlingFilter:filterName=throttling-filter.
```

-  My Blazegraph root folder from the `wikidata-query-rdf` distribution looks like:

```
-rw-r--r--  1 root root      3191 Mar 26 11:07 RWStore.properties
-rw-r--r--  1 root root  73200128 Mar 26 11:07 blazegraph-service-0.3.1-SNAPSHOT.war
-rwxr-xr-x  1 root root       369 Mar 26 11:07 createNamespace.sh
-rw-r--r--  1 root root      1483 Mar 26 11:07 default.properties
drwxr-xr-x  2 root root      4096 Mar 26 11:07 docs
-rwxr-xr-x  1 root root       318 Mar 26 11:07 forAllCategoryWikis.sh
drwxr-xr-x 11 root root      4096 Mar 28 08:27 gui
-rw-r--r--  1 root root   5248622 Mar 26 11:07 jetty-runner-9.2.3.v20140905.jar
-rwxr-xr-x  1 root root       208 Mar 26 11:07 jolokia.sh
-rw-r--r--  1 root root      2144 Mar 26 11:07 ldf-config.json.fail
drwxr-xr-x  2 root root      4096 Mar 26 11:07 lib
-rwxr-xr-x  1 root root       838 Mar 26 11:07 loadCategoryDump.sh
-rwxr-xr-x  1 root root       813 Mar 26 11:07 loadData.sh
-rwxr-xr-x  1 root root      1278 Mar 26 11:07 loadRestAPI.sh
-rwxr-xr-x  1 root root       767 Mar 26 11:07 munge.sh
-rw-------  1 root root    582776 Mar 28 08:27 nohup.out
-rw-r--r--  1 root root    425480 Mar 28 08:27 out.log
-rw-r--r--  1 root root         0 Mar 26 11:07 prefixes.conf
-rwxr-xr-x  1 root root      3056 Mar 26 11:07 runBlazegraph.sh
-rwxr-xr-x  1 root root      2023 Mar 26 11:07 runUpdate.sh
-rw-r--r--  1 root root 209715200 Mar 28 08:25 wikidata.jnl
```

-  I have my wikidata dump and split in a separate volume:

```
root@e46c552b99d7:~/blazegraph# ls -l /root/data/
total 33378472
drwxr-xr-x 2 root root       36864 Mar 27 20:56 split
-rw-r--r-- 1 1000 1000 34179509561 Mar 23 07:10 wikidata-20180319-all-BETA.ttl.gz
root@e46c552b99d7:~/blazegraph# ls -l /root/data/split/
total 26481488
-rw-r--r-- 1 root root 186839974 Mar 27 07:48 wikidump-000000001.ttl.gz
-rw-r--r-- 1 root root 114197889 Mar 27 07:51 wikidump-000000002.ttl.gz
-rw-r--r-- 1 root root  82660694 Mar 27 07:53 wikidump-000000003.ttl.gz
...
-rw-r--r-- 1 root root  67287903 Mar 27 20:56 wikidump-000000475.ttl.gz
-rw-r--r-- 1 root root  12876417 Mar 27 20:56 wikidump-000000476.ttl.gz
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
I have found out the error! It was a typo in the import command!

So now I can see that all the process are running:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                 
  521 root      20   0 24.359g 0.011t  22420 S 323.3 69.3  10:52.10 java                                                                                                                                                                    
  597 root      20   0  159264   5464   4660 S   0.0  0.0   0:00.05 curl                                                                                                                                                                    
  111 root      20   0   18400   3508   2888 S   0.0  0.0   0:00.19 bash                                                                                                                                                                    
  637 root      20   0   36668   3124   2624 R   0.0  0.0   0:00.00 top                                                                                                                                                                     
  592 root      20   0   18044   2968   2712 S   0.0  0.0   0:00.00 loadRestAPI.sh                                                                                                                                                          
    1 root      20   0   18236   2836   2836 S   0.0  0.0   0:00.03 bash    
```

and the HTTP post that import that is working:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   409    0     0  100   409      0     28  0:00:14  0:00:14 --:--:--     0
100   409    0     0  100   409      0     25  0:00:16  0:00:16 --:--:--     0
```

I also can see that the journal file is growing, so I can assume that the import is going on:

```
root@e46c552b99d7:~/blazegraph# watch -n 15 ls -hl /root/data/wikidata.jnl
Every 15.0s: ls -hl /root/data/wikidata.jnl                                                                                                                                                                          Wed Mar 28 09:06:46 2018

-rw-r--r-- 1 root root 4.5G Mar 28 09:06 /root/data/wikidata.jnl
```

Is there any way to check from the Blazegraph API the status of the union :) ?

**Comment by loretoparisi** [comment]
Closing since this issue has been solved!
